apiVersion: v1
kind: Service
metadata:
  name: synthetic-insight-backend
  labels:
    app: synthetic-insight-backend
spec:
  selector:
    app: synthetic-insight-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
